version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    reviewers:
      - hatsu38
    open-pull-requests-limit: 10
    schedule:
      interval: monthly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    reviewers:
      - hatsu38
    open-pull-requests-limit: 10
    schedule:
      interval: monthly
